// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADeWsVGPY5Str0VS0aPP-YoKIhY31Z9Sg',
    appId: '1:518921820595:web:837d51198deaef594d53c6',
    messagingSenderId: '518921820595',
    projectId: 'quizapp-dc8ca',
    authDomain: 'quizapp-dc8ca.firebaseapp.com',
    storageBucket: 'quizapp-dc8ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHEM3h45Cw7QacpI6oiuhwx_OtxhPXvIE',
    appId: '1:518921820595:android:0cff88e5061a7d214d53c6',
    messagingSenderId: '518921820595',
    projectId: 'quizapp-dc8ca',
    storageBucket: 'quizapp-dc8ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZ7UMQYHDz7J-Ujr6Gc7tu7pfLEBK6ho',
    appId: '1:518921820595:ios:cece1792a47c07af4d53c6',
    messagingSenderId: '518921820595',
    projectId: 'quizapp-dc8ca',
    storageBucket: 'quizapp-dc8ca.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdZ7UMQYHDz7J-Ujr6Gc7tu7pfLEBK6ho',
    appId: '1:518921820595:ios:8400e724811a46194d53c6',
    messagingSenderId: '518921820595',
    projectId: 'quizapp-dc8ca',
    storageBucket: 'quizapp-dc8ca.appspot.com',
    iosBundleId: 'com.example.quizapp.RunnerTests',
  );
}
